name: Python Publish Workflow
on:
  pull_request:
  workflow_run:
    workflows:
      - "Linting and Tests"
    branches:
      - master
      - main
    types:
      - completed

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@v3
      - name: build
        run: pdm build
      - name: pypi-publish
        uses: pypa/gh-action-pypi-publish@v1.8.6
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
          verbose: true
