name: Python Publish Workflow
on:
  workflow_run:
    workflows:
      - Linting and Tests
    branches:
      - master
      - main
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@v3
      - run: |
          pdm build
          echo ${{ secrets.PYPI_USERNAME }}
          echo ${{ secrets.PYPI_PASSWORD }}
      - name: Publish package distributions to PyPI
        run: pdm publish
