name: Linting and Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]
  workflow_dispatch:

jobs:
  linting:
    name: Python 3.11 checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - uses: pre-commit/action@v3.0.0

  tests:
    name: Python 3.11 tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@v3
        with:
          python-version: 3.11
          cache: true
      - run: pdm install
      - run: pdm run pytest
