name: Linting and Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]
  workflow_dispatch:

jobs:
  checks:
    name: Python ${{ matrix.python_version }} checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.7, 3.8, 3.9, 3.10, 3.11]
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo ${{ secrets.PYPI_USERNAME }}
          echo ${{ secrets.PYPI_PASSWORD }}
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python_version }}
      - uses: pre-commit/action@v3.0.0
